name: ZITADEL CI/CD

on:
  push:
    tags-ignore:
      - "*"
    branches:
      - "main"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: write

jobs:
  core:
    uses: ./.github/workflows/core.yml
    with:
      node_version: "20"
      buf_version: "latest"
      go_version: "1.22"

  console:
    uses: ./.github/workflows/console.yml
    with:
      node_version: "20"
      buf_version: "latest"

  version:
    uses: ./.github/workflows/version.yml
    with:
      semantic_version: "23.0.7"
      dry_run: true

  compile:
    needs: [core, console, version]
    uses: ./.github/workflows/compile.yml
    with:
      go_version: "1.22"
      core_cache_key: ${{ needs.core.outputs.cache_key }}
      console_cache_key: ${{ needs.console.outputs.cache_key }}
      core_cache_path: ${{ needs.core.outputs.cache_path }}
      console_cache_path: ${{ needs.console.outputs.cache_path }}
      version: ${{ needs.version.outputs.version }}

  core-unit-test:
    needs: core
    uses: ./.github/workflows/core-unit-test.yml
    with:
      go_version: "1.22"
      core_cache_key: ${{ needs.core.outputs.cache_key }}
      core_cache_path: ${{ needs.core.outputs.cache_path }}

  lint:
    needs: [core, console]
    uses: ./.github/workflows/lint.yml
    with:
      go_version: "1.22"
      node_version: "18"
      buf_version: "latest"
      go_lint_version: "v1.55.2"
      core_cache_key: ${{ needs.core.outputs.cache_key }}
      core_cache_path: ${{ needs.core.outputs.cache_path }}

  container:
    needs: [compile]
    uses: ./.github/workflows/container.yml
    secrets: inherit
    permissions:
      packages: write
    if: ${{ github.event_name == 'workflow_dispatch' }}
    with:
      build_image_name: "ghcr.io/hyunrealshadow/zitadel-build"
